Feature/112 credential library
verida/verida-js pull request #116
Opened 2021-12-09 07:33 UTC by cmcWebCode40

- Resolved designed issue as suggested https://github.com/verida/verida-js/issues/113#issuecomment-989507537
- Modified tests to work on the new design

Resolves #112

2021-12-09 07:59 UTC, tahpot requested changes
@cmcWebCode40 See my review comments.

The unit tests need to also pass.

2021-12-09 07:59 UTC, tahpot commented on packages/verifiable-credentials/src/sharing-credential.ts
> +	async issueEncryptedCredential(didJwtVc: string): Promise<any> {
This needs to pass the full `item`.

2021-12-09 07:59 UTC, tahpot commented on packages/verifiable-credentials/src/sharing-credential.ts
> +	async fetchCredentialURI(uri: string): Promise<string> {
Move this into `client-ts::Utils`

2021-12-09 08:05 UTC, cmcWebCode40 commented
@tahpot 
Noted will resolve 

But I tested the unit test and all passed , what error did you get ?

2021-12-09 08:12 UTC, tahpot commented
@cmcWebCode40 my mistake. I hadn't rebuilt `client-ts`.

2021-12-09 08:33 UTC, tahpot commented
@cmcWebCode40 Once this is done, can you provide instructions on how this works in our documentation?

@pkhien95 Can then use this to generate a URL to display in a QR code on the credential screen in the vault.

2021-12-09 08:36 UTC, cmcWebCode40 commented
Yes I can provide instructions on how it works , but do i need to edit the docs from notion directly?

2021-12-09 08:45 UTC, tahpot commented
Yes, you'll need to edit Notion directly.

Add to the Verifiable Credentials section and then tag me in slack.

2021-12-09 10:35 UTC, cmcWebCode40 commented
@tahpot, 

i have modified requested changes ,

2021-12-09 11:04 UTC, cmcWebCode40 commented
@tahpot , 

I don't think i have access to edit our documentation on notion

2021-12-10 03:04 UTC, tahpot commented
Some feedback:

- Be consistent with casing `URI` or `Uri`? (I prefer `Uri` as that's what has been used elsewhere)
- `utils.fetchCredentialURI()` -- Need to throw an exception if the item isn't found or if the data can't be decrypted. Add unit tests for these edge cases.
- `utils.getUrlByPath()` -- Rename to `explodeVeridaUri()`
- `utils.generateObjectUri()` -- Rename to `buildVeridaUri()`
- `utils.fetchCredentialURI()` -- Rename to `fetchVeridaUri()`

2021-12-10 03:17 UTC, cmcWebCode40 commented
noted, will make changes

2021-12-10 06:31 UTC, cmcWebCode40 commented
@tahpot ,

update requested changes

2021-12-10 21:19 UTC, tahpot commented
@cmcWebCode40 This is good work :)

I have made a few final changes, please review and you can then merge.

2021-12-10 22:11 UTC, merged

2021-12-10 22:11 UTC, cmcWebCode40 commented
Reviewed