Feature/185 update create credential jwt
verida/verida-js pull request #187
Opened 2022-04-25 06:42 UTC by cmcWebCode40

- [x] Added veridaContextName in vc object

2022-04-27 01:22 UTC, tahpot approved these changes
Thanks @cmcWebCode40 -- looks good :)

2022-04-29 03:47 UTC, cmcWebCode40 commented
@tahpot, 

The new change I made was to modify the` createCredentialJWT()` method so it accepts the `veridaContextName` used in opening a  public profile.

## The Issue 

- We tried sending creating a VC from the `demo-credential`  app, but the logged-in `issuer`'s profile `contextName` from the demo-app, is `Verida: Vault` meanwhile the library tries to use the issuer app `contextName`   which is `Verida: Verifiable Credential Demo` different from the profile contextName  `Verida: Vault`, this caused an error in the account-explorer-demo because it was unable to look up the profile with the app `contextName` (Verida: Verifiable Credential ).

But this works for the `credential-mgt-platform` demo because the same app contextName was for used setting a public profile.

## Solution
So we have to pass the  profile `contextName` as an argument in the` createCredentialJWT()` which solves this problem

what are your thoughts on this approach?

2022-05-11 04:26 UTC, tahpot commented
@cmcWebCode40 

No, this change is not correct.

The `account-explorer-demo` needs to lookup the the profile with the app context name (Verida: Verifiable Credential). If not found, it needs to lookup `Verida: Vault` as a fallback.

This is the logic used by the Vault.

2022-05-11 04:56 UTC, cmcWebCode40 commented
> so we may need to consider a bit of tooling in the SDK to make this easier?
 using the Verida: Vault as a fallback sounds good I will have to test again and  @andy-verida will test as well in the vault.

2022-05-11 08:11 UTC, andy-verida commented
@tahpot, @cmcWebCode40 and I tested together and confirm the fallback approach to the default context `Verida: Vault` works. the code looks sth like this
```
const MAX_PROFILE_RETRY = 2
export async function getPublicProfile(
  did: string,
  contextName = VERIDA_CONTEXT_NAME
) {
  let ctxName = contextName
  const retryNumber = ctxName === VERIDA_CONTEXT_NAME ? 1 : MAX_PROFILE_RETRY
  const client = AccountManager.getInstance().getClient()
  for (let t = 1; t <= retryNumber; t++) {
    if (t === MAX_PROFILE_RETRY) {
      ctxName = VERIDA_CONTEXT_NAME
    }

    try {
      const publicProfile = await client?.openPublicProfile(
        did,
        ctxName,
        'basicProfile'
      )
      const name = await publicProfile?.get('name')
      const avatar = await publicProfile?.get('avatar')

      return {
        name: name || 'Unknown',
        avatar: avatar || DefaultAvatar,
      }
    } catch (error: any) {
      Sentry.captureException(error)
    }
  }
}
```

2022-05-12 22:57 UTC, tahpot commented
> Though I prefer code to be implemented at the app level, but not sure should we make it into the `openPublicProfile` function inside client lib so we can avoid repeating code in many apps?

I think this will be a common issue, so yes lets do that.

What if there is an extra fourth parameter to `openPublicProfile()` called `fallbackContext = "Verida: Vault"`?

It will default to "Verida: Vault", but could be set to nothing if the app doesn't want the fallback.

@andy-verida Feel free to create an issue and PR with that change if you agree.

2022-05-13 04:07 UTC, andy-verida commented
> What if there is an extra fourth parameter to `openPublicProfile()` called `fallbackContext = "Verida: Vault"`?

@tahpot looks good, I created a new issue here https://github.com/verida/verida-js/issues/194

2022-05-19 09:35 UTC, tahpot requested changes
This can not be approved as it adds `issuerName` functionality that is not necessary.

2022-05-19 09:47 UTC, tahpot commented on packages/verifiable-credentials/test/create-credentials.test.ts
> +            appContext = await connectAccount(config.PRIVATE_KEY_1, config.VERIDA_CONTEXT_NAME, EnvironmentType.TESTNET, config.ISSUER_NAME);
issuer name

2022-05-19 09:48 UTC, tahpot requested changes
Tagging issuer name references

2022-05-19 09:48 UTC, tahpot commented on packages/verifiable-credentials/src/utils.ts
> +export async function connectAccount(privateKey: string, contextName: string, environment: EnvironmentType, issuerName: string): Promise<Context> {
issuer name

2022-05-19 09:48 UTC, tahpot commented on packages/verifiable-credentials/test/share-credentials.test.ts
> +            appContext = await connectAccount(config.PRIVATE_KEY_1, config.VERIDA_CONTEXT_NAME, EnvironmentType.TESTNET, config.ISSUER_NAME);
issuer name

2022-05-19 10:04 UTC, tahpot approved these changes
Thanks @cmcWebCode40, all approved.

2022-05-19 10:05 UTC, merged