Added verida custom button
verida/verida-js pull request #75
Opened 2021-10-14 09:38 UTC by cmcWebCode40

- Added verida custom button,  so that developers can pass and id `verida-button` to an html input tag 

resolves #65

2021-10-14 23:45 UTC, nick-verida commented
I'm not able to give any useful feedback on this, sorry. I don't know TS or how the library works. 

Happy to verify it works if there is a test harness, but beyond that I don't think I'm useful.

@tahpot will need to review.

2021-11-02 01:21 UTC, tahpot commented
@cmcWebCode40 

Any reason `addVeridaButtonImage()` is called three times?

I would have thought the image would be injected once when the page loads?

2021-11-02 01:28 UTC, cmcWebCode40 commented
> @cmcWebCode40
> 
> Any reason `addVeridaButtonImage()` is called three times?
> 
> I would have thought the image would be injected once when the page loads?

ok, I noticed that the verida button image gets removed from the DOM whenever the modal is closed.
what way I can resolve this to call the function once?

2021-11-02 02:24 UTC, cmcWebCode40 commented
> addVeridaButtonImage()

@tahpot  here is a short demo ,

https://www.loom.com/share/fb97130c9cfc4018acf56510a9785e9f

i called the function once on-load ,but whenever i open and close the QR modal the button unmount , that was why i called the addVeridaButtonImage() , when the modal is clicked .

2021-11-02 02:49 UTC, tahpot commented
As discussed, let's undo this and just provide a static image asset for developers to copy and past and include that in the docs.

2021-11-02 23:27 UTC, cmcWebCode40 commented
> As discussed, let's undo this and just provide a static image asset for developers to copy and paste and include that in the docs.

@taphot, this PR has been updated with the requested changes.

2021-11-23 06:50 UTC, tahpot requested changes

2021-11-23 06:50 UTC, tahpot commented on packages/account-web-vault/README.md
> +<img src="https://assets.verida.io/connect-button.png" alt="Verida Vault App" />
@cmcWebCode40 @nick-verida 

`https://assets.verida.io/connect-button.png` does not exist

2021-11-23 14:20 UTC, cmcWebCode40 commented
@tahpot , thanks

changes requests noted
i will resolve them

2021-12-02 21:41 UTC, nick-verida commented
@cmcWebCode40 do you know what the status of this is?

2022-01-11 23:34 UTC, nick-verida commented
@cmcWebCode40 @tahpot Does this need merging?

2022-01-19 03:19 UTC, nick-verida commented
Looks like this is redundant.

2022-01-19 03:19 UTC, closed without merging